version: '3'
services:
  dev:
    image: rammohan478/devrepo:latest
    ports:
      - "95:80"
    deploy:
      replicas: 3

  test:
    image: rammohan478/testrepo:latest
    ports:
      - "96:80"
    deploy:
      replicas: 3

  uat:
    image: rammohan478/uatrepo:latest
    ports:
      - "97:80"
    deploy:
      replicas: 3

  
