version: '3'
services:
  dev:
    image: rammohan478/devrepo:latest
    ports:
      - "90:80"
    deploy:
      replicas: 3

  test:
    image: rammohan478/testrepo:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3

  uat:
    image: rammohan478/uatrepo:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3

  
